## Chapter 1

In [46]:
import numpy as np

array1=np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:', array1. shape)

array2=np.array([[1,2,3],
                [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:', array2. shape)

array3=np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:', array3. shape)

print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,
                                                         array2.ndim,array3.ndim))

list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

list2=[1,2,'test']
array2=np.array(list2)
print(array2,array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)

array1=np.arange(start=1, stop=10)
print('array1:',array1)

value=array1[2]
print('value:', value)
print(type(value))

array1[0]=9
array1[8]=0
print('array1:',array1)

array3=array1[0:3]
print(array3)
print(type(array3))
array4=array1[:3]
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d[0:2,0:2])
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 
      'array2d[1] shape:', array2d[1].shape)

org_array=np.array([3,1,9,5])
print('원본 행렬:', org_array)
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬행렬:', sort_array1)

titanic_df=pd.read_csv('titanic_train.csv')
titanic_df.head(3)
titanic_df.describe()
titanic_df[0:2]
titanic_df[titanic_df['Age']>60][['Name','Age']].head(3)
titanic_df[(titanic_df['Age']>60)&(titanic_df['Pclass']==1)&(titanic_df['Sex']=='female')]
titanic_sorted=titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)
titanic_groupby=titanic_df.groupby(by='Pclass')
titanic_groupby=titanic_df.groupby(by='Pclass').count()
titanic_df.groupby=titanic_df.groupby('Pclass')['Age'].agg([max,min])
titanic_df.isna().head(3)
titanic_df.isna().sum()
titanic_df['Age']=titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked']=titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1: 1차원, array2: 2차원, array3:  2차원
<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32
['1' '2' 'test'] <U11
[1. 2. 3.] float64
array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
array1: [9 2 3 4 5 6 7 8 0]
[9 2 3]
<class 'numpy.ndarray'>
array2d:
 [[1 2]
 [4 5]]
[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)
원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬행렬: [1 3 5 9]


## chapter 2

### 붓꽃 품종 예측하기

In [4]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

import pandas as pd
iris=load_iris()
iris_data=iris.data
iris_label=iris.target
iris_df=pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(3)

X_train, X_test, y_train, y_test = train_test_split(iris_data,iris_label,
                                                   test_size=0.2, random_state=11)
dt_clf=DecisionTreeClassifier(random_state=11)
dt_clf.fit(X_train, y_train)
pred=dt_clf.predict(X_test)
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

### 데이터 전처리

In [21]:
#레이블 인코딩
from sklearn.preprocessing import LabelEncoder
items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서','믹서']
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print('인코딩 변환값:', labels)

#원-핫 인코딩
from sklearn.preprocessing import OneHotEncoder
import numpy as np
items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서','믹서']
items=np.array(items).reshape(-1,1)
oh_encoder=OneHotEncoder()
oh_encoder.fit(items)
oh_labels=oh_encoder.transform(items)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)
df=pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서','믹서']})
pd.get_dummies(df)

#StandardScaler
iris=load_iris()
iris_data=iris.data
iris_df=pd.DataFrame(data=iris_data, columns=iris.feature_names)
print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)
iris_df_scaled=pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature 들의 분산 값')
print(iris_df_scaled.var())

#MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)
iris_df_scaled=pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들의 최솟값')
print(iris_df_scaled.min())
print('\nfeature 들의 최댓값')
print(iris_df_scaled.max())

인코딩 변환값: [0 1 4 5 3 3 2 2 2]
원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(9, 6)
feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64
feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64
feature 들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: flo

## Chapter 3

### 피마 인디언 당뇨병 예측

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
from sklearn.metrics import f1_score, confusion_matrix, precision_recall_curve, roc_curve
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

diabetes_data=pd.read_csv('diabetes.csv')
print(diabetes_data['Outcome'].value_counts())
diabetes_data.head(3)

diabetes_data.info()

X=diabetes_data.iloc[:,:-1]
y=diabetes_data.iloc[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=156,stratify=y)
lr_clf=LogisticRegression(solver='linear')
lr_clf.fit(X_train,y_train)
pred=lr_clf.predict(X_test)
pred_proba=lr_clf.predict_proba(X_test)[:,1]
get_clf_eval(y_test,pred,pred_proba)

pred_proba_c1=lr_clf.predict_proba(X_test)[:,1]
precision_recall_curve_plot(y_test,pred_proba_c1)

diabetes_data.describe()
plt.hist(diabetes_data['Glucos'],bins=100)
plt.show()

zero_features=['Glucose','BloodPressure','SkinThickness','Insulin','BMI']
total_count=diabetes_data['Glucose'].count()
for feature in zero_features:
    zero_count=diabetes_data[diabetes_data[feature]==0][feature].count()
    print('{0} 0 건수는 {1}, 퍼센트는 {2:.2f}%'.format(feature,zero_count,100*zero_count/total_count))
    
mean_zero_features=diabetes_data[zero_features].mean()
diabetes_data[zero_features]=diabetes_data[zero_features].replace(0,mean_zero_features)

X=diabetes_data.iloc[:,:-1]
y=diabetes_data.iloc[:,-1]
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.2,random_state=156,stratify=y)
lr_clf=LogisticRegression()
lr_clf.fit(X_train,y_train)
pred=lr_clf.predict(X_test)
pred_proba=lr_clf.predict_proba(X_test)[:,1]
get_clf_eval(y_test,pred,pred_proba)

thresholds=[0.3,0.33,0.36,0.39,0.42,0.45,0.48,0.50]
pred_proba=lr_clf.predict_proba(X_test)
get_eval_by_threshold(y_test,pred_proba[:,1].reshape(-1,1),thresholds)

binarizer=Binarizer(threshold=0.48)

pred_th_0488=binarizer.fit_transform(pred_proba[:,1].reshape(-1,1))
get_clf_eval(y_test,pred_th_048,pred_proba[:,1])